[tool.ruff]
cache-dir = "build/.cache/ruff"
ignore = [
  # robot framework convention
  "N999",
  # mutually-exclusive with other options
  "D211",
  "D213",
  # trust black
  "E501",
  # keep 3.8 compat
  "UP006",
  "UP007",
]
select = [
  "A",
  "ARG",
  "B",
  "BLE",
  "C4",
  "C90",
  "COM",
  "D",
  "DJ",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  # "FBT",
  "G",
  "I",
  "ICN",
  "INP",
  "ISC",
  "N",
  "NPY",
  "PD",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "SLF",
  "T10",
  "T20",
  "TCH",
  "TID",
  # "TRY",
  "UP",
  "W",
  "YTT",
]

[tool.ruff.per-file-ignores]
"_scripts/*.py" = [
  "E722", "N812", "PLR0912", "C901", "T201", "BLE001", "S603", "S101", "S607",
  "DTZ005", "PLC1901", "S110"
]
"conf.py" = ["T201", "A001", "INP001", "S603", "DTZ005"]
"dodo.py" = ["E722", "E501", "T201", "S603", "RET504", "N812"]
"JupyterLibrary/__init__.py" = ["N999"]
