channels:
  - conda-forge
  - nodefaults
  - conda-forge/label/notebook_beta
dependencies:
  # enough stuff to run doit
  - doit-with-toml
  - pip
  - pyyaml
  # really nothing for it
  - nodejs >=18,<19
  # hard deps
  - robotframework >=4
  - robotframework-seleniumlibrary >=4.5
