channels:
  - conda-forge
  - nodefaults
dependencies:
  # enough stuff to run doit
  - doit
  - pip
  - pyyaml
  # really nothing for it
  - nodejs >=16,!=17.*,!=19.*
  # hard deps
  - robotframework >=4
  - robotframework-seleniumlibrary >=4.5
