dependencies:
  - jupyter_server >=1.2
  - jupyterlab >=3.6.4,<4.0.0a0
  - notebook >=6.0.0,<7.0.0a0
  - jupyterlab_server >=2.0.0,<3.0.0a0
  # next roadmap item
  - ipywidgets >=8,<9 # ...with whatever version of...
  # ... jupyterlab_widgets     # it brings along
  # developer experience stuff
  - jupyterlab_robotmode >=0.2.0,<1.0.0a0
