dependencies:
  - jupyter_server >=1.2
  - jupyterlab >=4.0.1,<5.0.0a0
  - notebook >=7.0.0b3,<8.0.0a0
  - jupyterlab_server >=2.0.0,<3.0.0a0
  # next roadmap item
  - ipywidgets >=8,<9 # ...with whatever version of...
  # ... jupyterlab_widgets     # it brings along
