channels:
  - conda-forge
  - nodefaults

dependencies:
  - boa >=0.14,<0.15
  # known-incompatible version with conda-lock
  - conda <22.11.1
  - conda-lock >=1.4,<1.5
  - mamba >=1.4.0,<1.5
  - doit-with-toml
  - pip
  - ripgrep
  - twine
