channels:
  - conda-forge
  - nodefaults

dependencies:
  - boa >=0.14,<0.15
  - conda <22.11.1 # known-incompatible version with conda-lock
  - conda-lock >=2.1,<2.2
  - doit-with-toml
  - flit >=3.9,<4.0
  - mamba >=1.4.0,<1.5
  - pip
  - ripgrep
  - twine
