channels:
  - conda-forge
  - nodefaults

dependencies:
  - boa >=0.11,<0.12
  - conda >=4.14,<4.15
  - conda-lock >=1.1.1,<2
  - conda-verify
  - doit
  - mamba >=0.25,<0.26
  - pip
  - ripgrep
  - twine
