channels:
  - conda-forge
  - nodefaults

dependencies:
  - boa >=0.9,<0.10
  - conda >=4.11,<4.12
  - conda-build >=3.21,<3.22
  - conda-lock >=0.13.2,<0.14
  - conda-verify
  - doit >=0.34,<0.35
  - mamba >=0.21.2,<0.22
  - pip >=0.34
  - ripgrep
  - twine
