channels:
  - conda-forge
  - nodefaults

dependencies:
  - boa >=0.14,<0.15
  # known-incompatible version with conda-lock
  - conda !=22.11.1
  - conda-lock >=1.3,<1.4
  - mamba >=1.1.0,<1.2
  - doit
  - pip
  - ripgrep
  - twine
