*** Settings ***
Documentation       Common selectors for Lumino elements


*** Variables ***
${LM CSS MOD CURRENT}           .lm-mod-current
${LM CSS MOD HIDDEN}            .lm-mod-hidden

${LM CSS TAB}                   .lm-TabBar-tab
${LM CSS CMD INPUT}             .lm-CommandPalette-input
${LM CSS CMD ITEM}              .lm-CommandPalette-item
${LM CSS MENU}                  .lm-MenuBar-menu
${LM CSS MENU ITEM LABEL}       .lm-Menu-itemLabel
